/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLoader: typeof import('./../src/components/AppLoader.vue')['default']
    ContactsMemoryUsage: typeof import('./../src/views/contacts/components/ContactsMemoryUsage.vue')['default']
    ContactsTable: typeof import('./../src/views/contacts/components/ContactsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
